/*
Copyright 2017 The Nuclio Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

version = '1.2.0'

def sonatypeUsernameWithFallback = project.ext.properties.sonatypeUsername
def sonatypePasswordWithFallback = project.ext.properties.sonatypePassword

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.junit.platform:junit-platform-gradle-plugin:1.0.1'
    }
}

apply plugin: 'java'
apply plugin: 'maven-publish'
apply plugin: 'signing'

apply plugin: 'org.junit.platform.gradle.plugin'

task sourceJar(type: Jar) {
    archiveClassifier.set("sources")
    from sourceSets.main.allJava
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier.set("javadoc")
    from javadoc.destinationDir
}

artifacts {
    archives jar
    archives sourceJar
    archives javadocJar
}

signing {
    // Check if signing properties are available and sign the archives
    if (project.hasProperty('signing.keyId') && project.hasProperty('signing.secretKeyRingFile') && project.hasProperty('signing.password')) {
        useGpgCmd()  // Use the GPG command line tool to sign artifacts
        sign configurations.archives
    }
}

dependencies {
    testImplementation(
        'org.junit.jupiter:junit-jupiter-api:5.8.2'
    )
    testRuntimeOnly(
        'org.junit.jupiter:junit-jupiter-engine:5.8.2',
    )
}

repositories {
    mavenCentral()
}

jar {
    manifest {
        attributes 'Implementation-Title': 'nuclio-sdk',
                   'Implementation-Version': version,
                   'Implementation-Vendor': 'io.nuclio'
    }
    version = version
    archivesBaseName = 'nuclio-sdk'
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            customizePom(pom)
            groupId 'io.nuclio'
            artifactId 'nuclio-sdk-java'
            version version

            from components.java

            artifact(sourceJar) {
                classifier = 'sources'
            }
            artifact(javadocJar) {
                classifier = 'javadoc'
            }
            repositories {
                maven {
                    url "https://oss.sonatype.org/service/local/staging/deploy/maven2"
                    credentials {
                        username sonatypeUsernameWithFallback
                        password sonatypePasswordWithFallback
                    }
                }
            }

            // Create the signed pom artifact
            pom.withXml {
                def pomFile = file("${project.buildDir}/generated-pom.xml")
                writeTo(pomFile)
                def pomAscFile = signing.sign(pomFile).signatureFiles[0]
                artifact(pomAscFile) {
                    classifier = null
                    extension = 'pom.asc'
                }
            }
            // Create the signed artifacts for sources and javadoc
            tasks.withType(Sign).configureEach {
                if (it.name == "signArchives") {
                    it.doLast {
                        project.tasks.withType(Jar).matching { it.name.contains("sources") || it.name.contains("javadoc") }.each { jarTask ->
                            signing.sign(jarTask)
                        }
                    }
                }
            }
        }
    }
}

def customizePom(pom) {
    pom.withXml {
        def root = asNode()

        // Eliminate test-scoped dependencies (no need in Maven Central POMs)
        root.dependencies.removeAll { dep ->
            dep.scope == "test"
        }

        // Add all items necessary for Maven Central publication
        root.children().last() + {
            resolveStrategy = Closure.DELEGATE_FIRST

            description 'Nuclio Java SDK'
            name 'Nuclio Java SDK'
            url 'https://github.com/nuclio/nuclio-sdk-java'
            organization {
                name 'io.nuclio'
                url 'https://github.com/nuclio'
            }
            issueManagement {
                system 'GitHub'
                url 'https://github.com/nuclio/nuclio-sdk-java'
            }
            licenses {
                license {
                    name 'Apache License 2.0'
                    url 'https://github.com/nuclio/nuclio-sdk-java/blob/master/LICENSE'
                    distribution 'repo'
                }
            }
            scm {
                url 'https://github.com/nuclio/nuclio-sdk-java'
                connection 'scm:git:git://github.com/nuclio/nuclio-sdk-java.git'
                developerConnection 'scm:git:git@github.com:nuclio/nuclio-sdk-java.git'
            }
            developers {
                developer {
                    name 'Miki Tebeka'
                }
                developer {
                    name 'Gal Topper'
                }
            }
        }
    }
}

model {
    tasks.generatePomFileForMavenJavaPublication {
        destination = file("$buildDir/generated-pom.xml")
    }
    tasks.publishMavenJavaPublicationToMavenLocal {
        dependsOn project.tasks.signArchives
    }
    tasks.publishMavenJavaPublicationToMavenRepository {
        dependsOn project.tasks.signArchives
    }
}
